<?php

namespace Tests\Feature;

use Coyote\User;
use Faker\Factory;
use Tests\TestCase;

class JobApiTest extends TestCase
{
    private $token;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = factory(User::class)->create();
        $this->token = $user->createToken('4programmers.net')->accessToken;
    }

    public function testSubmitJob()
    {
        $faker = Factory::create();

        $data = [
            'title' => $faker->title,
            'salary_from' => 3000,
            'salary_to' => 5000
        ];

        $response = $this->json('POST', '/v1/jobs', $data, ['Authorization' => 'Bearer ' . $this->token, 'Accept' => 'application/json', 'Content-Type' => 'application/json']);

        $this->assertEquals(201, $response->getStatusCode());
        $response->assertJsonFragment(['title' => $data['title']]);
    }
}
